### ISSUE TITLE
install fails on node 4.0.0

### ISSUE THREAD

**Issue by karissa** [mafintosh/hyperfs#6]
```
.....bunch of junk....
n file included from ../fuse-bindings.cc:1:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/karissa/.node-gyp/4.0.0/src/node.h:42:
/Users/karissa/.node-gyp/4.0.0/deps/v8/include/v8.h:221:5: error:
      assigning to 'v8::Object *volatile' from incompatible type
      'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/karissa/.node-gyp/4.0.0/deps/v8/include/v8.h:180:37: note:
      expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1776:12: note: in instantiation of
      function template specialization
      'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro
      'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsu...
                             ^
12 errors generated.
make: *** [Release/obj.target/fuse_bindings/fuse-bindings.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
 stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/hyperfs/node_modules/fuse-bindings
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok

> mknod@1.1.0 install /usr/local/lib/node_modules/hyperfs/node_modules/mknod
> prebuild --download

-
> leveldown@1.4.1 install /usr/local/lib/node_modules/hyperfs/node_modules/level/node_modules/leveldown
> prebuild --download

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "hyperfs"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! fuse-bindings@2.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fuse-bindings@2.6.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fuse-bindings package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fuse-bindings
npm ERR! There is likely additional logging output above.
rm -r
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/karissa/dev/node_modules/dat/npm-debug.log
```

**Comment by maxogden** [comment]
found a relevant upstream issue https://github.com/mafintosh/fuse-bindings/issues/6

**Comment by ralphtheninja** [comment]
@karissa Can we close this? I just checked and it compiles fine on my machine (using linux though and not os x)
